/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Process is up */
    get: operations['getHealthLive'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Dependencies (Postgres, Redis, S3) are reachable */
    get: operations['getHealthReady'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealthLive: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            status: 'ok';
          };
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code:
                | 'VALIDATION_FAILED'
                | 'UNAUTHENTICATED'
                | 'TOKEN_EXPIRED'
                | 'FORBIDDEN_ROLE'
                | 'NO_ACTIVE_ORG'
                | 'NOT_FOUND'
                | 'ILLEGAL_TRANSITION'
                | 'TRIP_CANCELLED'
                | 'TRIP_REASSIGNED'
                | 'VEHICLE_BUSY'
                | 'DRIVER_BUSY'
                | 'CANCELLATION_PENDING'
                | 'ALREADY_SETTLED'
                | 'IDEMPOTENCY_CONFLICT'
                | 'IDEMPOTENCY_KEY_REQUIRED'
                | 'VERSION_CONFLICT'
                | 'CONFLICT'
                | 'FUEL_TYPE_MISMATCH'
                | 'ODOMETER_BEFORE_START'
                | 'OTP_INVALID'
                | 'OTP_EXPIRED'
                | 'RATE_LIMITED'
                | 'UPLOAD_NOT_FOUND'
                | 'UPLOAD_MISMATCH'
                | 'INTERNAL';
              message: string;
              details?: unknown;
              requestId?: string;
            };
          };
        };
      };
    };
  };
  getHealthReady: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ok' | 'error';
            checks: {
              /** @enum {string} */
              postgres: 'ok' | 'error';
              /** @enum {string} */
              redis: 'ok' | 'error';
              /** @enum {string} */
              s3: 'ok' | 'error';
            };
          };
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code:
                | 'VALIDATION_FAILED'
                | 'UNAUTHENTICATED'
                | 'TOKEN_EXPIRED'
                | 'FORBIDDEN_ROLE'
                | 'NO_ACTIVE_ORG'
                | 'NOT_FOUND'
                | 'ILLEGAL_TRANSITION'
                | 'TRIP_CANCELLED'
                | 'TRIP_REASSIGNED'
                | 'VEHICLE_BUSY'
                | 'DRIVER_BUSY'
                | 'CANCELLATION_PENDING'
                | 'ALREADY_SETTLED'
                | 'IDEMPOTENCY_CONFLICT'
                | 'IDEMPOTENCY_KEY_REQUIRED'
                | 'VERSION_CONFLICT'
                | 'CONFLICT'
                | 'FUEL_TYPE_MISMATCH'
                | 'ODOMETER_BEFORE_START'
                | 'OTP_INVALID'
                | 'OTP_EXPIRED'
                | 'RATE_LIMITED'
                | 'UPLOAD_NOT_FOUND'
                | 'UPLOAD_MISMATCH'
                | 'INTERNAL';
              message: string;
              details?: unknown;
              requestId?: string;
            };
          };
        };
      };
    };
  };
}
