/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Process is up */
    get: operations['getHealthLive'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Dependencies (Postgres, Redis, S3) are reachable */
    get: operations['getHealthReady'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/otp/request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send a one-time login code by SMS */
    post: operations['postAuthOtpRequest'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/otp/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange a login code for a session (creates the user on first login) */
    post: operations['postAuthOtpVerify'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate the refresh token and get a new access token */
    post: operations['postAuthRefresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke the refresh token (and every token rotated from it) */
    post: operations['postAuthLogout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/switch-org': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Get a session scoped to another org you belong to */
    post: operations['postAuthSwitchorg'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The signed-in user and their memberships */
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update your profile */
    patch: operations['patchMe'];
    trace?: never;
  };
  '/orgs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create an organization; you become its owner (and driver, for a DCO) */
    post: operations['postOrgs'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealthLive: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            status: 'ok';
          };
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code:
                | 'VALIDATION_FAILED'
                | 'UNAUTHENTICATED'
                | 'TOKEN_EXPIRED'
                | 'FORBIDDEN_ROLE'
                | 'NO_ACTIVE_ORG'
                | 'NOT_FOUND'
                | 'ILLEGAL_TRANSITION'
                | 'TRIP_CANCELLED'
                | 'TRIP_REASSIGNED'
                | 'VEHICLE_BUSY'
                | 'DRIVER_BUSY'
                | 'CANCELLATION_PENDING'
                | 'ALREADY_SETTLED'
                | 'IDEMPOTENCY_CONFLICT'
                | 'IDEMPOTENCY_KEY_REQUIRED'
                | 'VERSION_CONFLICT'
                | 'CONFLICT'
                | 'FUEL_TYPE_MISMATCH'
                | 'ODOMETER_BEFORE_START'
                | 'OTP_INVALID'
                | 'OTP_EXPIRED'
                | 'RATE_LIMITED'
                | 'UPLOAD_NOT_FOUND'
                | 'UPLOAD_MISMATCH'
                | 'INTERNAL';
              message: string;
              details?: unknown;
              requestId?: string;
            };
          };
        };
      };
    };
  };
  getHealthReady: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ok' | 'error';
            checks: {
              /** @enum {string} */
              postgres: 'ok' | 'error';
              /** @enum {string} */
              redis: 'ok' | 'error';
              /** @enum {string} */
              s3: 'ok' | 'error';
            };
          };
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code:
                | 'VALIDATION_FAILED'
                | 'UNAUTHENTICATED'
                | 'TOKEN_EXPIRED'
                | 'FORBIDDEN_ROLE'
                | 'NO_ACTIVE_ORG'
                | 'NOT_FOUND'
                | 'ILLEGAL_TRANSITION'
                | 'TRIP_CANCELLED'
                | 'TRIP_REASSIGNED'
                | 'VEHICLE_BUSY'
                | 'DRIVER_BUSY'
                | 'CANCELLATION_PENDING'
                | 'ALREADY_SETTLED'
                | 'IDEMPOTENCY_CONFLICT'
                | 'IDEMPOTENCY_KEY_REQUIRED'
                | 'VERSION_CONFLICT'
                | 'CONFLICT'
                | 'FUEL_TYPE_MISMATCH'
                | 'ODOMETER_BEFORE_START'
                | 'OTP_INVALID'
                | 'OTP_EXPIRED'
                | 'RATE_LIMITED'
                | 'UPLOAD_NOT_FOUND'
                | 'UPLOAD_MISMATCH'
                | 'INTERNAL';
              message: string;
              details?: unknown;
              requestId?: string;
            };
          };
        };
      };
    };
  };
  postAuthOtpRequest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          phone: string;
        };
      };
    };
    responses: {
      /** @description OK */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            expiresInSeconds: number;
            resendAfterSeconds: number;
          };
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code:
                | 'VALIDATION_FAILED'
                | 'UNAUTHENTICATED'
                | 'TOKEN_EXPIRED'
                | 'FORBIDDEN_ROLE'
                | 'NO_ACTIVE_ORG'
                | 'NOT_FOUND'
                | 'ILLEGAL_TRANSITION'
                | 'TRIP_CANCELLED'
                | 'TRIP_REASSIGNED'
                | 'VEHICLE_BUSY'
                | 'DRIVER_BUSY'
                | 'CANCELLATION_PENDING'
                | 'ALREADY_SETTLED'
                | 'IDEMPOTENCY_CONFLICT'
                | 'IDEMPOTENCY_KEY_REQUIRED'
                | 'VERSION_CONFLICT'
                | 'CONFLICT'
                | 'FUEL_TYPE_MISMATCH'
                | 'ODOMETER_BEFORE_START'
                | 'OTP_INVALID'
                | 'OTP_EXPIRED'
                | 'RATE_LIMITED'
                | 'UPLOAD_NOT_FOUND'
                | 'UPLOAD_MISMATCH'
                | 'INTERNAL';
              message: string;
              details?: unknown;
              requestId?: string;
            };
          };
        };
      };
    };
  };
  postAuthOtpVerify: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          phone: string;
          code: string;
          /** Format: uuid */
          deviceId: string;
          /** @enum {string} */
          platform: 'android' | 'ios' | 'web';
          appVersion?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
            user: {
              /** Format: uuid */
              id: string;
              phone: string;
              name: string | null;
            };
            activeOrgId: string | null;
            memberships: {
              /** Format: uuid */
              orgId: string;
              orgName: string;
              /** @enum {string} */
              orgKind: 'fleet' | 'dco';
              roles: ('owner' | 'manager' | 'driver')[];
            }[];
          };
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code:
                | 'VALIDATION_FAILED'
                | 'UNAUTHENTICATED'
                | 'TOKEN_EXPIRED'
                | 'FORBIDDEN_ROLE'
                | 'NO_ACTIVE_ORG'
                | 'NOT_FOUND'
                | 'ILLEGAL_TRANSITION'
                | 'TRIP_CANCELLED'
                | 'TRIP_REASSIGNED'
                | 'VEHICLE_BUSY'
                | 'DRIVER_BUSY'
                | 'CANCELLATION_PENDING'
                | 'ALREADY_SETTLED'
                | 'IDEMPOTENCY_CONFLICT'
                | 'IDEMPOTENCY_KEY_REQUIRED'
                | 'VERSION_CONFLICT'
                | 'CONFLICT'
                | 'FUEL_TYPE_MISMATCH'
                | 'ODOMETER_BEFORE_START'
                | 'OTP_INVALID'
                | 'OTP_EXPIRED'
                | 'RATE_LIMITED'
                | 'UPLOAD_NOT_FOUND'
                | 'UPLOAD_MISMATCH'
                | 'INTERNAL';
              message: string;
              details?: unknown;
              requestId?: string;
            };
          };
        };
      };
    };
  };
  postAuthRefresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          refreshToken: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
            user: {
              /** Format: uuid */
              id: string;
              phone: string;
              name: string | null;
            };
            activeOrgId: string | null;
            memberships: {
              /** Format: uuid */
              orgId: string;
              orgName: string;
              /** @enum {string} */
              orgKind: 'fleet' | 'dco';
              roles: ('owner' | 'manager' | 'driver')[];
            }[];
          };
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code:
                | 'VALIDATION_FAILED'
                | 'UNAUTHENTICATED'
                | 'TOKEN_EXPIRED'
                | 'FORBIDDEN_ROLE'
                | 'NO_ACTIVE_ORG'
                | 'NOT_FOUND'
                | 'ILLEGAL_TRANSITION'
                | 'TRIP_CANCELLED'
                | 'TRIP_REASSIGNED'
                | 'VEHICLE_BUSY'
                | 'DRIVER_BUSY'
                | 'CANCELLATION_PENDING'
                | 'ALREADY_SETTLED'
                | 'IDEMPOTENCY_CONFLICT'
                | 'IDEMPOTENCY_KEY_REQUIRED'
                | 'VERSION_CONFLICT'
                | 'CONFLICT'
                | 'FUEL_TYPE_MISMATCH'
                | 'ODOMETER_BEFORE_START'
                | 'OTP_INVALID'
                | 'OTP_EXPIRED'
                | 'RATE_LIMITED'
                | 'UPLOAD_NOT_FOUND'
                | 'UPLOAD_MISMATCH'
                | 'INTERNAL';
              message: string;
              details?: unknown;
              requestId?: string;
            };
          };
        };
      };
    };
  };
  postAuthLogout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          refreshToken: string;
        };
      };
    };
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code:
                | 'VALIDATION_FAILED'
                | 'UNAUTHENTICATED'
                | 'TOKEN_EXPIRED'
                | 'FORBIDDEN_ROLE'
                | 'NO_ACTIVE_ORG'
                | 'NOT_FOUND'
                | 'ILLEGAL_TRANSITION'
                | 'TRIP_CANCELLED'
                | 'TRIP_REASSIGNED'
                | 'VEHICLE_BUSY'
                | 'DRIVER_BUSY'
                | 'CANCELLATION_PENDING'
                | 'ALREADY_SETTLED'
                | 'IDEMPOTENCY_CONFLICT'
                | 'IDEMPOTENCY_KEY_REQUIRED'
                | 'VERSION_CONFLICT'
                | 'CONFLICT'
                | 'FUEL_TYPE_MISMATCH'
                | 'ODOMETER_BEFORE_START'
                | 'OTP_INVALID'
                | 'OTP_EXPIRED'
                | 'RATE_LIMITED'
                | 'UPLOAD_NOT_FOUND'
                | 'UPLOAD_MISMATCH'
                | 'INTERNAL';
              message: string;
              details?: unknown;
              requestId?: string;
            };
          };
        };
      };
    };
  };
  postAuthSwitchorg: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          refreshToken: string;
          /** Format: uuid */
          orgId: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
            user: {
              /** Format: uuid */
              id: string;
              phone: string;
              name: string | null;
            };
            activeOrgId: string | null;
            memberships: {
              /** Format: uuid */
              orgId: string;
              orgName: string;
              /** @enum {string} */
              orgKind: 'fleet' | 'dco';
              roles: ('owner' | 'manager' | 'driver')[];
            }[];
          };
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code:
                | 'VALIDATION_FAILED'
                | 'UNAUTHENTICATED'
                | 'TOKEN_EXPIRED'
                | 'FORBIDDEN_ROLE'
                | 'NO_ACTIVE_ORG'
                | 'NOT_FOUND'
                | 'ILLEGAL_TRANSITION'
                | 'TRIP_CANCELLED'
                | 'TRIP_REASSIGNED'
                | 'VEHICLE_BUSY'
                | 'DRIVER_BUSY'
                | 'CANCELLATION_PENDING'
                | 'ALREADY_SETTLED'
                | 'IDEMPOTENCY_CONFLICT'
                | 'IDEMPOTENCY_KEY_REQUIRED'
                | 'VERSION_CONFLICT'
                | 'CONFLICT'
                | 'FUEL_TYPE_MISMATCH'
                | 'ODOMETER_BEFORE_START'
                | 'OTP_INVALID'
                | 'OTP_EXPIRED'
                | 'RATE_LIMITED'
                | 'UPLOAD_NOT_FOUND'
                | 'UPLOAD_MISMATCH'
                | 'INTERNAL';
              message: string;
              details?: unknown;
              requestId?: string;
            };
          };
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: {
              /** Format: uuid */
              id: string;
              phone: string;
              name: string | null;
            };
            activeOrgId: string | null;
            roles: ('owner' | 'manager' | 'driver')[];
            memberships: {
              /** Format: uuid */
              orgId: string;
              orgName: string;
              /** @enum {string} */
              orgKind: 'fleet' | 'dco';
              roles: ('owner' | 'manager' | 'driver')[];
            }[];
          };
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code:
                | 'VALIDATION_FAILED'
                | 'UNAUTHENTICATED'
                | 'TOKEN_EXPIRED'
                | 'FORBIDDEN_ROLE'
                | 'NO_ACTIVE_ORG'
                | 'NOT_FOUND'
                | 'ILLEGAL_TRANSITION'
                | 'TRIP_CANCELLED'
                | 'TRIP_REASSIGNED'
                | 'VEHICLE_BUSY'
                | 'DRIVER_BUSY'
                | 'CANCELLATION_PENDING'
                | 'ALREADY_SETTLED'
                | 'IDEMPOTENCY_CONFLICT'
                | 'IDEMPOTENCY_KEY_REQUIRED'
                | 'VERSION_CONFLICT'
                | 'CONFLICT'
                | 'FUEL_TYPE_MISMATCH'
                | 'ODOMETER_BEFORE_START'
                | 'OTP_INVALID'
                | 'OTP_EXPIRED'
                | 'RATE_LIMITED'
                | 'UPLOAD_NOT_FOUND'
                | 'UPLOAD_MISMATCH'
                | 'INTERNAL';
              message: string;
              details?: unknown;
              requestId?: string;
            };
          };
        };
      };
    };
  };
  patchMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            phone: string;
            name: string | null;
          };
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code:
                | 'VALIDATION_FAILED'
                | 'UNAUTHENTICATED'
                | 'TOKEN_EXPIRED'
                | 'FORBIDDEN_ROLE'
                | 'NO_ACTIVE_ORG'
                | 'NOT_FOUND'
                | 'ILLEGAL_TRANSITION'
                | 'TRIP_CANCELLED'
                | 'TRIP_REASSIGNED'
                | 'VEHICLE_BUSY'
                | 'DRIVER_BUSY'
                | 'CANCELLATION_PENDING'
                | 'ALREADY_SETTLED'
                | 'IDEMPOTENCY_CONFLICT'
                | 'IDEMPOTENCY_KEY_REQUIRED'
                | 'VERSION_CONFLICT'
                | 'CONFLICT'
                | 'FUEL_TYPE_MISMATCH'
                | 'ODOMETER_BEFORE_START'
                | 'OTP_INVALID'
                | 'OTP_EXPIRED'
                | 'RATE_LIMITED'
                | 'UPLOAD_NOT_FOUND'
                | 'UPLOAD_MISMATCH'
                | 'INTERNAL';
              message: string;
              details?: unknown;
              requestId?: string;
            };
          };
        };
      };
    };
  };
  postOrgs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          refreshToken: string;
          name: string;
          /** @enum {string} */
          kind: 'fleet' | 'dco';
        };
      };
    };
    responses: {
      /** @description OK */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
            user: {
              /** Format: uuid */
              id: string;
              phone: string;
              name: string | null;
            };
            activeOrgId: string | null;
            memberships: {
              /** Format: uuid */
              orgId: string;
              orgName: string;
              /** @enum {string} */
              orgKind: 'fleet' | 'dco';
              roles: ('owner' | 'manager' | 'driver')[];
            }[];
          };
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: {
              /** @enum {string} */
              code:
                | 'VALIDATION_FAILED'
                | 'UNAUTHENTICATED'
                | 'TOKEN_EXPIRED'
                | 'FORBIDDEN_ROLE'
                | 'NO_ACTIVE_ORG'
                | 'NOT_FOUND'
                | 'ILLEGAL_TRANSITION'
                | 'TRIP_CANCELLED'
                | 'TRIP_REASSIGNED'
                | 'VEHICLE_BUSY'
                | 'DRIVER_BUSY'
                | 'CANCELLATION_PENDING'
                | 'ALREADY_SETTLED'
                | 'IDEMPOTENCY_CONFLICT'
                | 'IDEMPOTENCY_KEY_REQUIRED'
                | 'VERSION_CONFLICT'
                | 'CONFLICT'
                | 'FUEL_TYPE_MISMATCH'
                | 'ODOMETER_BEFORE_START'
                | 'OTP_INVALID'
                | 'OTP_EXPIRED'
                | 'RATE_LIMITED'
                | 'UPLOAD_NOT_FOUND'
                | 'UPLOAD_MISMATCH'
                | 'INTERNAL';
              message: string;
              details?: unknown;
              requestId?: string;
            };
          };
        };
      };
    };
  };
}
